CREATE TABLE IF NOT EXISTS check_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    resource_name VARCHAR(255) NOT NULL,
    check_name VARCHAR(255) NOT NULL,
    check_type VARCHAR(64) NOT NULL,
    checked_at_epoch_ms BIGINT NOT NULL,
    successful BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    details CLOB,
    error_message CLOB
);

ALTER TABLE IF EXISTS check_results
    ADD COLUMN IF NOT EXISTS run_id VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_check_results_checked_at
    ON check_results (checked_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_check_results_resource_checked_at
    ON check_results (resource_name, checked_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_check_results_check_checked_at
    ON check_results (resource_name, check_name, checked_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_check_results_resource_run
    ON check_results (resource_name, run_id, checked_at_epoch_ms);
