CREATE TABLE IF NOT EXISTS check_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_name VARCHAR(255) NOT NULL,
    check_name VARCHAR(255) NOT NULL,
    check_type VARCHAR(64) NOT NULL,
    UNIQUE (resource_name, check_name)
);

CREATE TABLE IF NOT EXISTS check_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id BIGINT NOT NULL,
    checked_at_epoch_ms BIGINT NOT NULL,
    successful BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    details CLOB,
    error_message CLOB,
    CONSTRAINT fk_check_results_check
        FOREIGN KEY (check_id) REFERENCES check_definitions (id)
);

CREATE INDEX IF NOT EXISTS idx_check_definitions_resource_check
    ON check_definitions (resource_name, check_name);

CREATE INDEX IF NOT EXISTS idx_check_results_checked_at
    ON check_results (checked_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_check_results_check_checked_at
    ON check_results (check_id, checked_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_check_results_check_success_checked_at
    ON check_results (check_id, successful, checked_at_epoch_ms);

CREATE TABLE IF NOT EXISTS metric_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS metric_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id BIGINT NOT NULL,
    measured_at_epoch_ms BIGINT NOT NULL,
    metric_value DOUBLE PRECISION,
    successful BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    details CLOB,
    error_message CLOB,
    CONSTRAINT fk_metric_measurements_metric
        FOREIGN KEY (metric_id) REFERENCES metric_definitions (id)
);

CREATE INDEX IF NOT EXISTS idx_metric_definitions_name
    ON metric_definitions (metric_name);

CREATE INDEX IF NOT EXISTS idx_metric_measurements_measured_at
    ON metric_measurements (measured_at_epoch_ms);

CREATE INDEX IF NOT EXISTS idx_metric_measurements_metric_measured_at
    ON metric_measurements (metric_id, measured_at_epoch_ms);
