package net.edubovit.connectivity.monitor.data;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

import net.edubovit.connectivity.monitor.config.CheckType;
import net.edubovit.connectivity.monitor.service.CheckResult;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class CheckResultRepositoryTest {

    @Test
    void savesAndFindsResultsByTimeRange() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", ""));
        createSchema(jdbcTemplate);
        CheckResultRepository repository = new CheckResultRepository(jdbcTemplate);
        Instant checkedAt = Instant.parse("2026-04-28T10:00:00Z");

        repository.save("run-1", "example-resource", "homepage-get", CheckType.HTTP_GET.name(), checkedAt,
                new CheckResult(true, Duration.ofMillis(123), "status=200"));

        assertThat(repository.findBetween(
                Instant.parse("2026-04-28T09:59:00Z"),
                Instant.parse("2026-04-28T10:01:00Z")))
                .singleElement()
                .satisfies(result -> {
                    assertThat(result.runId()).isEqualTo("run-1");
                    assertThat(result.resourceName()).isEqualTo("example-resource");
                    assertThat(result.checkName()).isEqualTo("homepage-get");
                    assertThat(result.checkType()).isEqualTo("HTTP_GET");
                    assertThat(result.checkedAt()).isEqualTo(checkedAt);
                    assertThat(result.successful()).isTrue();
                    assertThat(result.durationMs()).isEqualTo(123);
                    assertThat(result.details()).isEqualTo("status=200");
                });
    }

    private void createSchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                CREATE TABLE check_results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id VARCHAR(64) NOT NULL,
                    resource_name VARCHAR(255) NOT NULL,
                    check_name VARCHAR(255) NOT NULL,
                    check_type VARCHAR(64) NOT NULL,
                    checked_at_epoch_ms BIGINT NOT NULL,
                    successful BOOLEAN NOT NULL,
                    duration_ms BIGINT NOT NULL,
                    details CLOB,
                    error_message CLOB
                )
                """);
    }
}
