package net.edubovit.connectivity.monitor.data;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

import net.edubovit.connectivity.monitor.service.MetricMeasurement;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class MetricMeasurementRepositoryTest {

    @Test
    void savesAndFindsMetricMeasurementsByTimeRange() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", ""));
        createSchema(jdbcTemplate);
        MetricMeasurementRepository repository = new MetricMeasurementRepository(jdbcTemplate);
        Instant measuredAt = Instant.parse("2026-04-28T10:00:00Z");

        repository.save("connection-count", measuredAt,
                new MetricMeasurement(12.0, true, Duration.ofMillis(45), "stdout=12", null));
        repository.save("connection-count", measuredAt.plusSeconds(60),
                new MetricMeasurement(null, false, Duration.ofMillis(50), "stdout=oops", "metric stdout is not a single numeric value"));

        assertThat(repository.findBetween(
                Instant.parse("2026-04-28T09:59:00Z"),
                Instant.parse("2026-04-28T10:02:00Z")))
                .hasSize(2)
                .satisfiesExactly(
                        measurement -> {
                            assertThat(measurement.metricName()).isEqualTo("connection-count");
                            assertThat(measurement.measuredAt()).isEqualTo(measuredAt);
                            assertThat(measurement.value()).isEqualTo(12.0);
                            assertThat(measurement.successful()).isTrue();
                            assertThat(measurement.durationMs()).isEqualTo(45);
                        },
                        measurement -> {
                            assertThat(measurement.value()).isNull();
                            assertThat(measurement.successful()).isFalse();
                            assertThat(measurement.errorMessage()).isEqualTo("metric stdout is not a single numeric value");
                        });
    }

    @Test
    void findsMetricMeasurementsOnlyForRequestedMetricNames() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", ""));
        createSchema(jdbcTemplate);
        MetricMeasurementRepository repository = new MetricMeasurementRepository(jdbcTemplate);
        Instant measuredAt = Instant.parse("2026-04-28T10:00:00Z");

        repository.save("configured", measuredAt,
                new MetricMeasurement(12.0, true, Duration.ofMillis(45), "stdout=12", null));
        repository.save("stale", measuredAt.plusSeconds(1),
                new MetricMeasurement(99.0, true, Duration.ofMillis(45), "stdout=99", null));

        assertThat(repository.findBetween(
                Instant.parse("2026-04-28T09:59:00Z"),
                Instant.parse("2026-04-28T10:02:00Z"),
                List.of("configured")))
                .singleElement()
                .satisfies(measurement -> assertThat(measurement.metricName()).isEqualTo("configured"));
        assertThat(repository.findBetween(
                Instant.parse("2026-04-28T09:59:00Z"),
                Instant.parse("2026-04-28T10:02:00Z"),
                List.of()))
                .isEmpty();
    }

    private void createSchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                CREATE TABLE metric_definitions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    metric_name VARCHAR(255) NOT NULL UNIQUE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE metric_measurements (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    metric_id BIGINT NOT NULL,
                    measured_at_epoch_ms BIGINT NOT NULL,
                    metric_value DOUBLE PRECISION,
                    successful BOOLEAN NOT NULL,
                    duration_ms BIGINT NOT NULL,
                    details CLOB,
                    error_message CLOB,
                    CONSTRAINT fk_metric_measurements_metric
                        FOREIGN KEY (metric_id) REFERENCES metric_definitions (id)
                )
                """);
    }
}
